### ISSUE TITLE
ruapu.h and main.c

### ISSUE THREAD

**Issue by nihui** [nihui/ruapu#2]

**Comment by nihui** [comment]
api name convention

`ruapu_<arch>_<isa>`

arch follows https://github.com/torvalds/linux/tree/master/arch

```c

int ruapu_x86_sse2();

int ruapu_x86_avx512f();

int ruapu_arm_neon();

int ruapu_arm64_asimdhp();


```

**Comment by nihui** [comment]
like gcc builtin funtion https://gcc.gnu.org/onlinedocs/gcc/x86-Built-in-Functions.html

```c
void __builtin_cpu_init();
int __builtin_cpu_supports(const char*);
```

ruapu provides the drop-in solution

```c
void __ruapu_cpu_init();
int __ruapu_cpu_supports(const char*);
```

**Comment by zchrissirhcz** [comment]
Where is the code...

**Comment by zchrissirhcz** [comment]
> Microsoft's compiler doesn't support inline assembly for x86-64 targets, as you said. This forces you to define your assembly functions in an external code module (*.asm), assemble them with MASM, and link the result together with your separately-compiled C/C++ code.

https://stackoverflow.com/questions/41208105/making-assembly-function-inline-in-x64-visual-studio

If the design of ruapu is "header-only library", then OS/Compiler specific APIs will be called instead of directly call `CPUID` in inline assembly, at least for x64 on MSVC.

**Comment by nihui** [comment]
Hi, the source code will be added after I sort it out   :D
