### ISSUE TITLE
Segmentation fault on s390x with `-O0`

### ISSUE THREAD

**Issue by cocoa-xu** [nihui/ruapu#45]
A weird segmentation fault on s390x machine if compiled with `-O0` (i.e., the default optimalisation level). Works fine with any other optimalisation level, like `-O3` or `-Os`.

```bash
$ gcc main.c -o ruapu
$ ./ruapu
Segmentation fault (core dumped)
$ gcc main.c -O3 -o ruapu
$ ./ruapu
zvector = 1
$ gcc main.c -Os -o ruapu
$ ./ruapu
zvector = 1
```

Tested on an s390x virtual machine on IBM Cloud.

GCC version:
```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/s390x-linux-gnu/11/lto-wrapper
Target: s390x-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=s390x-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch=z13 --with-tune=z15 --enable-s390-excess-float-precision --with-long-double-128 --enable-multilib --enable-checking=release --build=s390x-linux-gnu --host=s390x-linux-gnu --target=s390x-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
```

**Comment by ziyao233** [comment]
```
~/ruapu # gcc main.c -o main -O0
~/ruapu # ./main
zvector = 1
zvector
```
I cannot reproduce it on qemu-user-emulated s390x AlpineLinux edge with gcc 13.2.1, maybe this is a problem related to the compiler or libc

```
~/ruapu # gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/s390x-alpine-linux-musl/13.2.1/lto-wrapper
Target: s390x-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-13-20231014/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=s390x-alpine-linux-musl --host=s390x-alpine-linux-musl --target=s390x-alpine-linux-musl --enable-checking=release --disable-cet --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-languages=c,c++,d,objc,go,fortran,ada --enable-link-serialization=2 --enable-linker-build-id --with-arch=z196 --with-tune=zEC12 --with-zarch --with-long-double-128 --enable-decimal-float --disable-libquadmath --disable-libssp --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-bugurl=https://gitlab.alpinelinux.org/alpine/aports/-/issues --with-system-zlib --with-linker-hash-style=gnu --with-pkgversion='Alpine 13.2.1_git20231014'
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 13.2.1 20231014 (Alpine 13.2.1_git20231014) 
~/ruapu # apk version musl
Installed:                                Available:
musl-1.2.4_git20230717-r6               = 1.2.4_git20230717-r6 
```

**Comment by cocoa-xu** [comment]
> ```
> ~/ruapu # gcc main.c -o main -O0
> ~/ruapu # ./main
> zvector = 1
> zvector
> ```
> 
> I cannot reproduce it on qemu-user-emulated s390x AlpineLinux edge with gcc 13.2.1, maybe this is a problem related to the compiler or libc
> 
> ```
> ~/ruapu # gcc -v
> Using built-in specs.
> COLLECT_GCC=/usr/bin/gcc
> COLLECT_LTO_WRAPPER=/usr/libexec/gcc/s390x-alpine-linux-musl/13.2.1/lto-wrapper
> Target: s390x-alpine-linux-musl
> Configured with: /home/buildozer/aports/main/gcc/src/gcc-13-20231014/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=s390x-alpine-linux-musl --host=s390x-alpine-linux-musl --target=s390x-alpine-linux-musl --enable-checking=release --disable-cet --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-languages=c,c++,d,objc,go,fortran,ada --enable-link-serialization=2 --enable-linker-build-id --with-arch=z196 --with-tune=zEC12 --with-zarch --with-long-double-128 --enable-decimal-float --disable-libquadmath --disable-libssp --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-bugurl=https://gitlab.alpinelinux.org/alpine/aports/-/issues --with-system-zlib --with-linker-hash-style=gnu --with-pkgversion='Alpine 13.2.1_git20231014'
> Thread model: posix
> Supported LTO compression algorithms: zlib
> gcc version 13.2.1 20231014 (Alpine 13.2.1_git20231014) 
> ~/ruapu # apk version musl
> Installed:                                Available:
> musl-1.2.4_git20230717-r6               = 1.2.4_git20230717-r6 
> ```

It works with qemu emulated s390x but it seems to fail on a physical one. I compiled a statically linked ruapu binary in a s390x Alpine Linux docker image and uploaded it to the physical machine, and it also segfault'ed.

In the docker container,

```bash
$ gcc main.c -static -o ruapu
$ file ruapu
ruapu: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, BuildID[sha1]=9898843bbbcba13fa2be86b57e43e55606bf54bc, with debug_info, not stripped
```

scp it to the server and run it

```bash
$ file /tmp/ruapu
/tmp/ruapu: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, BuildID[sha1]=9898843bbbcba13fa2be86b57e43e55606bf54bc, with debug_info, not stripped
$ /tmp/ruapu
Segmentation fault
```

**Comment by nihui** [comment]
reproduced on travis ci s390x
https://app.travis-ci.com/github/nihui/ruapu/jobs/618524136

**Comment by nihui** [comment]
https://github.com/nihui/ruapu/pull/61

**Comment by cocoa-xu** [comment]
#61 fixed this issue! Tested on a physical s390x machine. ;)
