### ISSUE TITLE
python ruapu.rua() returns all supported isa features as one tuple

### ISSUE THREAD

**Issue by nihui** [nihui/ruapu#48]
```python
import ruapu

feats = ruapu.rua()
print(feats)

# ('mmx', 'sse', 'sse2', ....)
```

**Comment by cocoa-xu** [comment]
Wondering if this could be in the ruapu's C API so that other language bindings can also use it?

**Comment by nihui** [comment]
> Wondering if this could be in the ruapu's C API so that other language bindings can also use it?

https://github.com/nihui/ruapu/pull/52
