### ISSUE TITLE
It seems that ruapu has broken the std::chrono clock of mingw64

### ISSUE THREAD

**Issue by TianZerL** [nihui/ruapu#94]
使用mingw64 gcc13.2 (Windows 11)，运行 `ruapu_init()` 后会让`std::chrono`无法正确计算时间，返回`nan`

mingw64 Clang也有问题, 详见[godbolt](https://godbolt.org/z/chq6ecY3M)

---------------------------
I'm using mingw64 with gcc 13.2 (Windows 11), and run  `ruapu_init()` will make `std::chrono` clock return `nan`.

mingw64 with Clang also has this issue, example in [godbolt](https://godbolt.org/z/chq6ecY3M)

---------------------------
```c++
#include <chrono>
#include <cstdio>

#define RUAPU_IMPLEMENTATION
#include "ruapu.h"

struct Timer {
    std::chrono::time_point<std::chrono::high_resolution_clock> start = std::chrono::high_resolution_clock::now();
    ~Timer()
    {
        auto end = std::chrono::high_resolution_clock::now();
        std::chrono::duration<double, std::milli> duration = end - start;
        std::printf("Timer took %lfms\n", duration.count());
    }
};

int main()
{
    ruapu_init();
    {
        Timer timer{};
    }
    return 0;
}

```

![image](https://github.com/nihui/ruapu/assets/41182852/938d720a-7bf3-43e6-8821-ae3db70ee547)

**Comment by nihui** [comment]
confirmed

**Comment by nihui** [comment]
修好了，请测试下
